//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmography.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmStudios
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Workers_FK { get; set; }
    
        public virtual Workers Workers { get; set; }
    }
}
