//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmography.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Displays = new HashSet<Display>();
            this.Translations = new HashSet<Translation>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> YearRelease { get; set; }
        public Nullable<int> Genres_FK { get; set; }
        public Nullable<int> Country_FK { get; set; }
        public Nullable<int> FilmStudios_FK { get; set; }
        public Nullable<int> Viewers { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Display> Displays { get; set; }
        public virtual FilmStudio FilmStudio { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Translation> Translations { get; set; }
    }
}
