//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmography.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Filmography : DbContext
    {
        public Filmography()
            : base("name=Filmography")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Display> Display { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<FilmStudios> FilmStudios { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Humans> Humans { get; set; }
        public virtual DbSet<Translations> Translations { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
