//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmography.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int id { get; set; }
        public Nullable<int> FilmStidios_FK { get; set; }
        public string Post { get; set; }
        public Nullable<int> Humans_FK { get; set; }
    
        public virtual FilmStudio FilmStudio { get; set; }
        public virtual Human Human { get; set; }
    }
}
